version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - examples

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  goimports:
    local-prefixes: github.com/suthio/tiktok-business-api-sdk/go_sdk

  revive:
    enable-all-rules: false
    rules:
      - name: var-naming
      - name: unused-parameter

  gocritic:
    enabled-checks:
      - ruleguard

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
        - gocritic
        - revive
    - path: examples/.*\.go$
      linters:
        - revive
    - text: "stutters"
      linters:
        - revive
    - text: "package-comments"
      linters:
        - revive
